.TH BROADCAST 3 "09 Jul 2016"

.SH NAME
broadcast \- returns broadcast address with IP and network mask

.SH SYNOPSIS
.BI "#include <ipcalc.h>"
.br
.BI "unsigned long broadcast (ulong " ip ", ulong " mask ");"

.SH DESCRIPTION
.BI boradcast
API returns broadcast address of subnet using with ip address and network mask

.SH "RETURN VALUE"
return
.BI "32 bit positive integer"
on success, and returns
.BI 0
on fails.

.SH EXAMPLE
.nf
#include <ipcalc.h>

int main (void) {
    char * ip = "192.168.10.131";
    char * mask = "255.255.255.192";
    ulong r;

    r = broadcast (ip2long (ip), ip2long (mask));
    printf ("BROADCAST ADDRESS: %s\n", long2ip (r));

    return 0;
}
.fi

.SH AUTHORS
JoungKyun.Kim <http://oops.org>

.SH BUGS
Report to https://github.com/Joungkyun/libipcalc/issues

.SH COPYRIGHT
Copyright (c) 2016 JoungKyun.Kim <http://oops.org>

This api is follows
.BI LGPL 2.1

.SH SEE ALSO
guess_netmask(3), network(3)
