.TH GUESS_NETMASK 3 "09 Jul 2016"

.SH NAME
guess_netmask \- returns minimum subnet mask that include range of ip address.

.SH SYNOPSIS
.BI "#include <ipcalc.h>"
.br
.BI "unsigned long guess_netmask (ulong " start ", ulong " end ");"

.SH DESCRIPTION
.BI guess_netmask
api is returns minimum subnet mask of subnet that includes given ip range.

.SH "RETURN VALUE"
.PP
return
.BI "32 bit positive integer"
on success, and returns
.BI 0
on fails.

.SH EXAMPLE
.nf
#include <ipcalc.h>

int main (void) {
    char * start = "192.168.10.131";
    char * end   = "192.168.10.144";
    ulong r;

    r = guess_netmask (ip2long (start), ip2long (end));
    printf ("SUBNET MASK: %s\n", long2ip (r));

    return 0;
}
.fi

.SH AUTHORS
JoungKyun.Kim <http://oops.org>

.SH BUGS
Report to https://github.com/Joungkyun/libipcalc/issues

.SH COPYRIGHT
Copyright (c) 2016 JoungKyun.Kim <http://oops.org>

This api is follows
.BI LGPL 2.1
