.TH NETMASK 3 "09 Jul 2016"

.SH NAME
guess_netmask \- convert IPv4 cidr address from Long IP

.SH SYNOPSIS
.BI "#include <ipcalc.h>"
.br
.BI "char * guess_netmask (ulong " start ", ulong " end ");"

.SH DESCRIPTION
.BI guess_netmask
api is returns minimum subnet mask of subnet that includes given ip range.

.SH "RETURN VALUE"
.PP
If success, returns
.BI "unsigned long"
format value, and  on fails, returns
.BI 0

.SH EXAMPLE
.nf
#include <ipcalc.h>

int main (void) {
    char * start = "192.168.10.131";
    char * end   = "192.168.10.144";
    ulong r;

    r = guess_netmask (ip2long (start), ip2long (end));
    printf ("SUBNET MASK: %s\n", long2ip (r));

    return 0;
}
.fi

.SH AUTHORS
JoungKyun.Kim <http://oops.org>

.SH BUGS
Report to QnA bulletin board of http://oops.org

.SH COPYRIGHT
Copyright (c) 2016 JoungKyun.Kim <http://oops.org>

This api is follows
.BI LGPL 2.1
