.TH IP2LONG 1 "09 Jul 2016"

.SH NAME
.BI ip2long
\- convert between 32bit positive integer and IPv4 dotted address

.SH SYNOPSIS
.BI "ip2long \-[hv] <" IP " " address "|" hostname "|" long " " ip ">"

.SH DESCRIPTION
.BI ip2long
command converts 4byte unsigned int address from IPv4 cddr address
or conversion as opposed.
.PP

.SH OPTIONS
.IP "-v"
Defaults,
.BI ip2long
returns converted value. If you give this option, retuns query value
and converted value.
.IP "-h"
print usage of ip2long

.SH AUTHORS
JoungKyun.Kim <http://oops.org>

.SH BUGS
Report to https://github.com/Joungkyun/libipcalc/issues

.SH COPYRIGHT
Copyright (c) 2016 JoungKyun.Kim <http://oops.org>

This api is follows
.BI GPL 2.1
