.TH NETCALC 1 "09 Jul 2016"

.SH NAME
.BI netcalc
\- Caculating utility for network
.SH SYNOPSIS
.BI "netcalc \-[abhmnps] " IP " " address "/[" mask "|" prefix "]"
.br
.BI "netcalc \-[abhmnps] " StartIP " " EndIP
.SH DESCRIPTION
.BI netcalc
provides a simple way to calculate IP information for a host. The various
options specify what information ipcalc should display on standard out.
Multiple options may be specified. An IP address to operate on must always
be specified. Most operations also require a netmask or a CIDR prefix as well.
.PP
.SH OPTIONS
.IP "-a"
sames -bmnp. print all options
.IP "-b"
print
.BI "broadcast address"
.IP "-m"
print
.BI "subnet mask address"
.IP "-n"
print
.BI "network address"
.IP "-p"
print
.BI CIDR
(network prefix)
.IP "-s"
print as
.BI "shell variable"
format
.IP "-h"
print help messages

.SH AUTHORS
JoungKyun.Kim <http://oops.org>

.SH BUGS
Report to https://github.com/Joungkyun/libipcalc/issues

.SH COPYRIGHT
Copyright (c) 2016 JoungKyun.Kim <http://oops.org>

This api is follows
.BI LGPL 2.1
