.TH NETCALC 1 "09 Jul 2016"

.SH NAME
.BI netcalc
\- Caculating utility for network
.SH SYNOPSIS
.BI "netcalc \-[abhmnps] " IP " " address "/[" mask "|" prefix "]"
.br
.BI "netcalc \-[abhmnps] " StartIP " " EndIP
.SH DESCRIPTION
.BI netcalc
Not yet
.PP
.SH OPTIONS
.IP "-a"
sames -bmnp. print all options
.IP "-b"
print broadcast address
.IP "-m"
print network mask address
.IP "-n"
print network address
.IP "-p"
print network prefix
.IP "-s"
print shell variable format
.IP "-h"
print help messages

.SH AUTHORS
JoungKyun.Kim <http://oops.org>

.SH BUGS
Report to https://github.com/Joungkyun/libipcalc/issues

.SH COPYRIGHT
Copyright (c) 2016 JoungKyun.Kim <http://oops.org>

This api is follows
.BI LGPL 2.1
