.TH PREFIX2LONG 3 "09 Jul 2016"

.SH NAME
.BI prefix2long
\- Converts network prefix to long mask.

.SH SYNOPSIS
.BI "#include <ipcalc.h>"
.br
.BI "ulong prefix2long (short * " prefix ");"

.SH DESCRIPTION
.BI prefix2long
api converts network prefix to 32bit positive integer mask.

.SH "RETURN VALUE"
.PP
return
.BI "32 bit positive integer"
on success, and returns
.BI 0
on fails.

.SH EXAMPLE
.nf
#include <ipcalc.h>

int main (void) {
    char * prefix = "24";
    ulong r;

    r = prefix2long ((short) atoi (prefix));
    printf ("LONG NETMASK: %ld\n", r);

    return 0;
}
.fi

.SH AUTHORS
JoungKyun.Kim <http://oops.org>

.SH BUGS
Report to https://github.com/Joungkyun/libipcalc/issues

.SH COPYRIGHT
Copyright (c) 2016 JoungKyun.Kim <http://oops.org>

This api is follows
.BI LGPL 2.1

.SH SEE ALSO
guess_netmask(3), long2prefix(3)
