#!/bin/sh
#
# $Id: autogen,v 1.1.1.1 2010-08-07 16:27:49 oops Exp $
# require autoconf > 2.59 & automake > 1.8

export LIBTOOL=/usr/bin/libtool
export AUTOMAKE=/usr/bin/automake
export ACLOCAL=/usr/bin/aclocal
rm -f configure autotool/{config.guess,config.sub,ltmain.sh}
autoreconf --install
rm -rf autom4te* *~

exit 0
