#!/bin/bash

CMD='dpkg-buildpackage -rfakeroot'
PROG="libipcalc"

usage() {
	echo "Usage: $0"
	exit 1
}

graceful_stop() {
	echo "**** graceful stop ****"
	pwd | grep 'debian$'
	[ $? -eq 0 ] && cd ..

	[ -f "debian/changelog.debbuild" ] && \
		echo "  * Rollback debian/changelog" && \
		mv debian/changelog.debbuild debian/changelog

	[ -f "Makefile" ] && \
		echo "  * Source cleaning" && \
		make distclean
	[ -n "$PROG" -a -d "debian/$PROG" ] && rm -rf debian/$PROG

	exit 1
}

trap 'graceful_stop' INT

echo "* $PROG debian package build script"
echo

[ "$1" = "-h" -o "$1" = "--help" ] && usage

if [ -f "/etc/lsb-release" ]; then
	source /etc/lsb-release
	distname="${DISTRIB_CODENAME}"
else
	distname="stable"
fi

if [ $# -eq 0 ]; then
	echo -n "  Distribution Name [default: ${distname}]: "
	read _distname
	[ -n "$_distname" ] && distname="${_distname}"
else
	distname=$1
fi

cd debian
cp -af changelog changelog.debbuild
perl -pi -e "s/\) stable; /\) ${distname}; /g" changelog
cd -

$CMD

[ $? -ne 0 ] && graceful_stop

cd debian
cp -af changelog.debbuild changelog
cd -
debian/rule clean
make distclean

exit 0
