.TH VALID_IP_ADDRESS 3 "10 Jan 2011"

.SH NAME
valid_ip_address \- validate IPv4 address or domain name.

.SH SYNOPSIS
.BI "#include <ipcalc.h>"
.br
.BI "short valid_ip_address (char * " address ", char * " err ");"

.SH DESCRIPTION
.BI valid_ip_address
api checks whether IPv4 address or domain name is valid or invalid.
If 1st argument value is domain name, this value is converted IPv4 address.

.SH "RETURN VALUE"
.PP
If given value is valid, returns 
.BI "0",
otherwise returns
.BI "1".

.SH EXAMPLE
.nf
#include <ipcalc.h>

int main (void) {
    //char addr[16] = "192.168.0.1";
    char addr[16] = "oops.org";
	char err[1024];
    char ip[16] = { 0, };
    ulong r;

    strcpy (ip, addr);
    if ( valid_ip_address (ip, err) ) {
        fprintf (stderr, "%s -> %s\n", addr, err);
        return 1;
    }

    printf ("IP address of %s is %s\n", addr, ip);

    return 0;
}
.fi

.SH AUTHORS
JoungKyun.Kim <http://oops.org>

.SH BUGS
Report to QnA bulletin board of http://oops.org

.SH COPYRIGHT
Copyright (c) 2011 JoungKyun.Kim <http://oops.org>

This api is follows
.BI LGPL 2.1
